services:
  - type: web
    name: swifly-manifest-site
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CACHE_SECONDS
        value: 30
