const crypto = require('crypto');
const express = require('express');
const JSZip = require('jszip');

const PORT = Number(process.env.PORT || 3000);
const APP_SECRET = process.env.APP_SECRET || 'dev-only-change-me';
const HEARTBEAT_TTL_SECONDS = Number(process.env.HEARTBEAT_TTL_SECONDS || 180);
const PUBLIC_BASE_URL = (process.env.PUBLIC_BASE_URL || '').replace(/\/$/, '');

const activeServers = new Map();

function base64urlJson(value) {
  return Buffer.from(JSON.stringify(value), 'utf8').toString('base64url');
}

function hmac(value) {
  return crypto.createHmac('sha256', APP_SECRET).update(value).digest('base64url');
}

function sign(payload) {
  const body = base64urlJson(payload);
  return `${body}.${hmac(body)}`;
}

function verify(token) {
  const [body, signature] = String(token || '').split('.');
  if (!body || !signature) return null;
  const expected = hmac(body);
  const a = Buffer.from(signature);
  const b = Buffer.from(expected);
  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null;
  try {
    return JSON.parse(Buffer.from(body, 'base64url').toString('utf8'));
  } catch {
    return null;
  }
}

function html(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function baseUrl(req) {
  return PUBLIC_BASE_URL || `${req.protocol}://${req.get('host')}`;
}

function clientIp(req) {
  const forwarded = req.header('x-forwarded-for');
  return forwarded ? forwarded.split(',')[0].trim() : (req.socket.remoteAddress || '');
}

function cleanString(value, fallback, max = 64) {
  const result = String(value || fallback || '').trim().slice(0, max);
  return result || fallback;
}

function toInt(value, fallback, min, max) {
  const n = Number.parseInt(value, 10);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(Math.max(n, min), max);
}

function serverFromForm(body) {
  const mode = ['zm', 'mp', 'cp'].includes(body.mode) ? body.mode : 'zm';
  return {
    id: crypto.randomUUID(),
    name: cleanString(body.name, 'Swifly Server', 64),
    mode,
    map: cleanString(body.map, mode === 'mp' ? 'mp_hunted' : 'zm_zod', 64),
    region: cleanString(body.region, '', 32),
    description: cleanString(body.description, '', 256),
    port: toInt(body.port, 27017, 1, 65535),
    players: 0,
    maxPlayers: toInt(body.maxPlayers, 8, 1, 64),
    passworded: body.passworded === 'on' || body.passworded === 'true',
    issuedAt: Date.now(),
  };
}

function publicServer(server) {
  return {
    id: server.id,
    name: server.name,
    address: server.address,
    port: server.port,
    mode: server.mode,
    map: server.map,
    region: server.region || '',
    description: server.description || '',
    players: server.players || 0,
    maxPlayers: server.maxPlayers || 8,
    passworded: Boolean(server.passworded),
    version: server.version || '',
    lastHeartbeatAt: server.lastHeartbeatAt,
  };
}

function pruneExpired() {
  const cutoff = Date.now() - HEARTBEAT_TTL_SECONDS * 1000;
  for (const [id, server] of activeServers.entries()) {
    if (!server.lastHeartbeatMs || server.lastHeartbeatMs < cutoff) activeServers.delete(id);
  }
}

function serverCfg(server) {
  const name = String(server.name || 'Swifly Server').replaceAll('"', "'");
  const map = String(server.map || 'zm_zod').replace(/[^a-zA-Z0-9_]/g, '');
  return [
    '// Generated by Swifly Server Registry',
    `set sv_hostname "${name}"`,
    `set live_steam_server_name "${name}"`,
    `set sv_maxclients "${server.maxPlayers || 8}"`,
    `set net_port "${server.port || 27017}"`,
    'set g_password ""',
    `set sv_maprotation "map ${map}"`,
    '',
  ].join('\r\n');
}

function heartbeatPs1(api, token, server) {
  const payload = {
    api,
    token,
    port: server.port,
    mode: server.mode,
    map: server.map,
    maxPlayers: server.maxPlayers,
  };

  return `$ErrorActionPreference = "Continue"\r\n\r\n$Config = @'\r\n${JSON.stringify(payload, null, 2)}\r\n'@ | ConvertFrom-Json\r\n\r\nWrite-Host "Swifly heartbeat running. Do not close this window."\r\n\r\nwhile ($true) {\r\n  try {\r\n    $Body = @{\r\n      port = [int]$Config.port\r\n      mode = [string]$Config.mode\r\n      map = [string]$Config.map\r\n      players = 0\r\n      maxPlayers = [int]$Config.maxPlayers\r\n      version = "swifly-oneclick-0.4.0"\r\n    } | ConvertTo-Json\r\n\r\n    Invoke-RestMethod -Method Post -Uri "$($Config.api)/api/heartbeat" -Headers @{ Authorization = "Bearer $($Config.token)" } -ContentType "application/json" -Body $Body | Out-Null\r\n    Write-Host "[$(Get-Date -Format T)] Listed on Swifly."\r\n  } catch {\r\n    Write-Warning "Heartbeat failed: $($_.Exception.Message)"\r\n  }\r\n\r\n  Start-Sleep -Seconds 30\r\n}\r\n`;
}

function startBat(server) {
  const cfg = server.mode === 'mp' ? 'server_mp.cfg' : 'server_zm.cfg';
  return `@echo off\r\nsetlocal\r\ntitle Swifly Server Launcher\r\ncd /d "%~dp0"\r\n\r\necho ========================================\r\necho        Swifly Server One-Click Kit\r\necho ========================================\r\necho.\r\necho Starting Swifly heartbeat...\r\nstart "Swifly Heartbeat" powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0heartbeat.ps1"\r\n\r\necho Starting server if a known executable exists...\r\nset SERVER_EXE=\r\nif exist "%~dp0swiflyboiii.exe" set SERVER_EXE=%~dp0swiflyboiii.exe\r\nif "%SERVER_EXE%"=="" if exist "%~dp0t7x.exe" set SERVER_EXE=%~dp0t7x.exe\r\nif "%SERVER_EXE%"=="" if exist "%~dp0BlackOps3_UnrankedDedicatedServer.exe" set SERVER_EXE=%~dp0BlackOps3_UnrankedDedicatedServer.exe\r\n\r\nif "%SERVER_EXE%"=="" (\r\n  echo Could not find swiflyboiii.exe, t7x.exe, or BlackOps3_UnrankedDedicatedServer.exe.\r\n  echo Put this kit in your server folder, then run this file again.\r\n  echo The heartbeat is still running if you started it.\r\n  pause\r\n  exit /b 1\r\n)\r\n\r\necho Found: %SERVER_EXE%\r\nstart "Swifly Game Server" "%SERVER_EXE%" -dedicated +set net_port ${server.port || 27017} +set logfile 2 +exec ${cfg}\r\n\r\necho.\r\necho Done. Keep the heartbeat window open.\r\npause\r\n`;
}

async function buildKit(req, server, token) {
  const api = baseUrl(req);
  const zip = new JSZip();
  zip.file('START_SWIFLY_SERVER.bat', startBat(server));
  zip.file('heartbeat.ps1', heartbeatPs1(api, token, server));
  zip.file('server_zm.cfg', serverCfg({ ...server, mode: 'zm' }));
  zip.file('server_mp.cfg', serverCfg({ ...server, mode: 'mp' }));
  zip.file('swifly_server.json', JSON.stringify({ api, token, ...server }, null, 2));
  zip.file('README_FIRST.txt', [
    'Swifly One-Click Server Kit',
    '',
    '1. Extract this ZIP into your BO3/Swifly dedicated server folder.',
    '2. Make sure swiflyboiii.exe, t7x.exe, or BlackOps3_UnrankedDedicatedServer.exe is in that folder.',
    '3. Double-click START_SWIFLY_SERVER.bat.',
    '4. Keep the heartbeat window open.',
    '5. Your server appears at:',
    `   ${api}/api/servers`,
    '',
    'This kit does not include BO3 game files or executables.',
  ].join('\r\n'));
  return zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
}

function page(title, body) {
  return `<!doctype html><html><head><title>${html(title)}</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:system-ui;background:#080a10;color:white;max-width:900px;margin:36px auto;padding:0 18px}.card{background:#141924;border:1px solid #293246;border-radius:18px;padding:24px;margin:18px 0}a{color:#8ab4ff}input,select,textarea{width:100%;box-sizing:border-box;padding:12px;border-radius:12px;border:1px solid #34405c;background:#0d111b;color:white;margin:6px 0 14px}button{background:#ff7a1a;color:white;border:0;border-radius:14px;padding:14px 18px;font-weight:800;font-size:16px;cursor:pointer}.steps{display:grid;gap:12px}.step{background:#0d111b;border-radius:14px;padding:14px}small{color:#aab4cc}pre{background:#0d111b;border-radius:12px;padding:14px;overflow:auto}</style></head><body>${body}</body></html>`;
}

const app = express();
app.set('trust proxy', true);
app.use(express.urlencoded({ extended: false }));
app.use(express.json({ limit: '64kb' }));

app.get('/health', (_req, res) => res.json({ ok: true, activeServers: activeServers.size }));

app.get('/', (req, res) => {
  res.type('html').send(page('Swifly Servers', `<h1>Swifly Server Hosting</h1><div class="card"><div class="steps"><div class="step"><strong>1.</strong> Create your server kit.</div><div class="step"><strong>2.</strong> Extract it into your server folder.</div><div class="step"><strong>3.</strong> Double-click <code>START_SWIFLY_SERVER.bat</code>.</div></div><p><a href="/host"><button>Create Server Kit</button></a></p><p><a href="/api/servers">View live Swifly server list</a></p></div>`));
});

app.get('/host', (_req, res) => {
  res.type('html').send(page('Create Server Kit', `<h1>Create Server Kit</h1><div class="card"><form method="post" action="/kit.zip"><label>Server name</label><input name="name" required minlength="3" maxlength="64" placeholder="Swifly Zombies #1"><label>Mode</label><select name="mode"><option value="zm">Zombies</option><option value="mp">Multiplayer</option><option value="cp">Campaign</option></select><label>Map</label><input name="map" value="zm_zod" required><details><summary>Advanced options</summary><label>Port</label><input name="port" type="number" min="1" max="65535" value="27017"><label>Max players</label><input name="maxPlayers" type="number" min="1" max="64" value="8"><label>Region</label><input name="region" placeholder="NA / EU / AU"><label>Description</label><textarea name="description" rows="3" maxlength="256"></textarea><label><input style="width:auto" type="checkbox" name="passworded"> Passworded</label></details><button type="submit">Download Server Kit</button></form></div><p><a href="/">Back</a></p>`));
});

app.post('/kit.zip', async (req, res, next) => {
  try {
    const server = serverFromForm(req.body || {});
    const token = sign({ id: server.id, server, issuedAt: Date.now() });
    const zip = await buildKit(req, server, token);
    res.setHeader('content-type', 'application/zip');
    res.setHeader('content-disposition', `attachment; filename="swifly-server-kit-${server.id}.zip"`);
    res.send(zip);
  } catch (err) {
    next(err);
  }
});

app.post('/api/heartbeat', (req, res) => {
  const header = req.header('authorization') || '';
  const token = header.match(/^Bearer\s+(.+)$/i)?.[1];
  const verified = verify(token);
  if (!verified?.server?.id) return res.status(401).json({ error: 'invalid token' });

  const now = Date.now();
  const update = req.body || {};
  const server = {
    ...verified.server,
    ...update,
    id: verified.server.id,
    address: update.address || clientIp(req),
    lastHeartbeatMs: now,
    lastHeartbeatAt: new Date(now).toISOString(),
  };
  activeServers.set(server.id, server);
  pruneExpired();
  res.json({ ok: true, server: publicServer(server) });
});

app.get('/api/servers', (_req, res) => {
  pruneExpired();
  res.json([...activeServers.values()].sort((a, b) => (b.lastHeartbeatMs || 0) - (a.lastHeartbeatMs || 0)).map(publicServer));
});

app.get('/servers', (_req, res) => {
  pruneExpired();
  const rows = [...activeServers.values()].map((s) => `<tr><td>${html(s.name)}</td><td>${html(s.mode)}</td><td>${html(s.map)}</td><td>${html(s.address)}:${html(s.port)}</td><td>${html(s.players || 0)}/${html(s.maxPlayers || 8)}</td></tr>`).join('');
  res.type('html').send(page('Live Servers', `<h1>Live Swifly Servers</h1><div class="card"><table width="100%"><tr><th align="left">Name</th><th align="left">Mode</th><th align="left">Map</th><th align="left">Address</th><th align="left">Players</th></tr>${rows || '<tr><td colspan="5">No servers online yet.</td></tr>'}</table></div><p><a href="/host">Create Server Kit</a></p>`));
});

app.use((err, _req, res, _next) => {
  console.error(err);
  res.status(500).send('Server error');
});

app.listen(PORT, '0.0.0.0', () => console.log(`Swifly one-click registry running on ${PORT}`));
