const crypto = require('crypto');
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const JSZip = require('jszip');
const { z } = require('zod');

const PORT = Number(process.env.PORT || 3000);
const APP_SECRET = process.env.APP_SECRET || process.env.ADMIN_API_KEY || 'dev-only-change-me';
const ADMIN_API_KEY = process.env.ADMIN_API_KEY || '';
const HEARTBEAT_TTL_SECONDS = Number(process.env.HEARTBEAT_TTL_SECONDS || 180);
const PUBLIC_BASE_URL = (process.env.PUBLIC_BASE_URL || '').replace(/\/$/, '');
const ALLOW_PUBLIC_SUBMISSIONS = (process.env.ALLOW_PUBLIC_SUBMISSIONS || 'true') === 'true';
const AUTO_VERIFY_PUBLIC_SUBMISSIONS = (process.env.AUTO_VERIFY_PUBLIC_SUBMISSIONS || 'true') === 'true';

const activeServers = new Map();

const serverSchema = z.object({
  name: z.string().trim().min(3).max(64),
  mode: z.enum(['mp', 'zm', 'cp']).default('zm'),
  map: z.string().trim().min(1).max(64).default('zm_zod'),
  gametype: z.string().trim().max(64).default(''),
  region: z.string().trim().max(32).default(''),
  description: z.string().trim().max(256).default(''),
  address: z.string().trim().max(128).optional(),
  port: z.number().int().min(1).max(65535).default(27017),
  players: z.number().int().min(0).max(64).default(0),
  maxPlayers: z.number().int().min(1).max(64).default(8),
  passworded: z.boolean().default(false),
  hidden: z.boolean().default(false),
  verified: z.boolean().default(true),
});

const heartbeatSchema = serverSchema.partial().extend({
  version: z.string().trim().max(64).optional(),
});

function base64urlJson(value) {
  return Buffer.from(JSON.stringify(value), 'utf8').toString('base64url');
}

function hmac(value) {
  return crypto.createHmac('sha256', APP_SECRET).update(value).digest('base64url');
}

function sign(payload) {
  const body = base64urlJson(payload);
  return `${body}.${hmac(body)}`;
}

function verify(token) {
  const [body, signature] = String(token || '').split('.');
  if (!body || !signature) return null;
  const expected = hmac(body);
  const a = Buffer.from(signature);
  const b = Buffer.from(expected);
  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null;
  try {
    return JSON.parse(Buffer.from(body, 'base64url').toString('utf8'));
  } catch {
    return null;
  }
}

function bearerToken(req) {
  const header = req.header('authorization') || '';
  const match = header.match(/^Bearer\s+(.+)$/i);
  return match ? match[1] : '';
}

function clientIp(req) {
  const forwarded = req.header('x-forwarded-for');
  return forwarded ? forwarded.split(',')[0].trim() : (req.socket.remoteAddress || '');
}

function baseUrl(req) {
  return PUBLIC_BASE_URL || `${req.protocol}://${req.get('host')}`;
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function requireAdmin(req, res, next) {
  if (!ADMIN_API_KEY) return res.status(500).json({ error: 'ADMIN_API_KEY is not configured' });
  if ((req.header('x-admin-key') || '') !== ADMIN_API_KEY) return res.status(401).json({ error: 'invalid admin key' });
  next();
}

function formToServerPayload(body, options = {}) {
  return serverSchema.parse({
    name: body.name,
    mode: body.mode || 'zm',
    map: body.map || 'zm_zod',
    gametype: body.gametype || '',
    region: body.region || '',
    description: body.description || '',
    port: Number(body.port || 27017),
    maxPlayers: Number(body.maxPlayers || 8),
    passworded: body.passworded === 'on' || body.passworded === 'true',
    players: 0,
    verified: options.verified ?? true,
    hidden: options.hidden ?? false,
  });
}

function publicServer(server) {
  return {
    id: server.id,
    name: server.name,
    address: server.address,
    port: server.port,
    mode: server.mode,
    map: server.map,
    gametype: server.gametype || '',
    region: server.region || '',
    description: server.description || '',
    players: server.players || 0,
    maxPlayers: server.maxPlayers || 8,
    passworded: Boolean(server.passworded),
    version: server.version || '',
    lastHeartbeatAt: server.lastHeartbeatAt,
  };
}

function pruneExpired() {
  const cutoff = Date.now() - HEARTBEAT_TTL_SECONDS * 1000;
  for (const [id, server] of activeServers.entries()) {
    if (!server.lastHeartbeatMs || server.lastHeartbeatMs < cutoff) activeServers.delete(id);
  }
}

function serverCfg(server) {
  const name = String(server.name || 'Swifly Server').replaceAll('"', "'");
  const map = String(server.map || 'zm_zod').replace(/[^a-zA-Z0-9_]/g, '');
  const maxPlayers = Number(server.maxPlayers || 8);
  const port = Number(server.port || 27017);
  return [
    '// Generated by Swifly Server Registry',
    `set sv_hostname "${name}"`,
    `set live_steam_server_name "${name}"`,
    `set sv_maxclients "${maxPlayers}"`,
    `set net_port "${port}"`,
    'set g_password ""',
    `set sv_maprotation "map ${map}"`,
    '',
  ].join('\r\n');
}

function heartbeatScript(apiUrl, token, server) {
  const safeApi = apiUrl.replaceAll('`', '');
  const safeToken = String(token).replaceAll('`', '');
  const mode = String(server.mode || 'zm').replaceAll('`', '');
  const map = String(server.map || 'zm_zod').replaceAll('`', '');
  const port = Number(server.port || 27017);
  const maxPlayers = Number(server.maxPlayers || 8);

  return `$ErrorActionPreference = "Stop"\r\n\r\n$Api = "${safeApi}"\r\n$Token = "${safeToken}"\r\n\r\nWrite-Host "Swifly heartbeat started."\r\nWrite-Host "Keep this window open while your server is running."\r\n\r\nwhile ($true) {\r\n  try {\r\n    $Body = @{\r\n      port = ${port}\r\n      mode = "${mode}"\r\n      map = "${map}"\r\n      players = 0\r\n      maxPlayers = ${maxPlayers}\r\n      version = "swifly-server-kit-0.3.0"\r\n    } | ConvertTo-Json\r\n\r\n    Invoke-RestMethod -Method Post -Uri "$Api/api/heartbeat" -Headers @{ Authorization = "Bearer $Token" } -ContentType "application/json" -Body $Body | Out-Null\r\n    Write-Host "Heartbeat OK $(Get-Date)"\r\n  } catch {\r\n    Write-Warning "Heartbeat failed: $($_.Exception.Message)"\r\n  }\r\n\r\n  Start-Sleep -Seconds 30\r\n}\r\n`;
}

async function makeServerKitZip(req, token, server) {
  const apiUrl = baseUrl(req);
  const zip = new JSZip();
  zip.file('README.txt', [
    'Swifly Server Kit',
    '',
    '1. Install BO3 / the unranked dedicated server legally.',
    '2. Put this kit in the same folder as your server files/configs.',
    '3. Use server_zm.cfg or server_mp.cfg as a starting point.',
    '4. Run Start-Heartbeat.bat while your server is online.',
    '5. Your server appears in Swifly after a successful heartbeat.',
    '',
    'This kit does not include BO3 game files or executables.',
  ].join('\r\n'));
  zip.file('swifly_server.json', JSON.stringify({ token, api: apiUrl, mode: server.mode, map: server.map, port: server.port }, null, 2));
  zip.file('heartbeat.ps1', heartbeatScript(apiUrl, token, server));
  zip.file('Start-Heartbeat.bat', '@echo off\r\npowershell -ExecutionPolicy Bypass -File "%~dp0heartbeat.ps1"\r\npause\r\n');
  zip.file('server_zm.cfg', serverCfg(server));
  zip.file('server_mp.cfg', serverCfg({ ...server, mode: 'mp' }));
  return zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
}

function makeServerAndToken(payload) {
  const id = crypto.randomUUID();
  const issuedAt = Date.now();
  const tokenPayload = {
    id,
    issuedAt,
    server: payload,
  };
  return {
    server: { id, ...payload, tokenIssuedAt: issuedAt },
    token: sign(tokenPayload),
  };
}

function tokenToServer(token) {
  const verified = verify(token);
  if (!verified || !verified.id || !verified.server) return null;
  return { id: verified.id, ...verified.server };
}

const app = express();
app.set('trust proxy', true);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(express.json({ limit: '64kb' }));
app.use(express.urlencoded({ extended: false }));
app.use(morgan('tiny'));

app.get('/health', (_req, res) => {
  res.json({ ok: true, service: 'swifly-server-registry-nodb', activeServers: activeServers.size });
});

app.get('/', (_req, res) => {
  res.type('html').send(`<!doctype html><html><head><title>Swifly Server Registry</title><style>body{font-family:system-ui;background:#0d0f16;color:#fff;max-width:900px;margin:40px auto;padding:0 20px}a{color:#8ab4ff}.card{background:#171b27;border:1px solid #2a3144;border-radius:16px;padding:22px;margin:18px 0}code{background:#0b0d13;padding:2px 6px;border-radius:6px}</style></head><body><h1>Swifly Server Registry</h1><div class="card"><p>Create a Swifly server entry, download its Server Kit, run the heartbeat, and your server appears in the Swifly-only list.</p><p><a href="/host">Create a server</a> · <a href="/api/servers">View public API list</a></p></div><div class="card"><p><strong>No database mode:</strong> the list is rebuilt from active server heartbeats. If the service restarts, running heartbeats re-add servers automatically.</p></div></body></html>`);
});

app.get('/host', (_req, res) => {
  res.type('html').send(`<!doctype html><html><head><title>Create Swifly Server</title><style>body{font-family:system-ui;background:#0d0f16;color:#fff;max-width:760px;margin:40px auto;padding:0 20px}label{display:block;margin:14px 0 6px}input,select,textarea{width:100%;box-sizing:border-box;padding:10px;border-radius:10px;border:1px solid #333;background:#111722;color:#fff}button{margin-top:18px;padding:12px 18px;border:0;border-radius:12px;background:#f47b20;color:#fff;font-weight:700}.card{background:#171b27;border:1px solid #2a3144;border-radius:16px;padding:22px}</style></head><body><h1>Create a Swifly Server</h1><div class="card"><form method="post" action="/host"><label>Server name</label><input name="name" placeholder="Swifly Zombies #1" required minlength="3" maxlength="64"><label>Mode</label><select name="mode"><option value="zm">Zombies</option><option value="mp">Multiplayer</option><option value="cp">Campaign</option></select><label>Map</label><input name="map" value="zm_zod" required><label>Region</label><input name="region" placeholder="NA / EU / AU"><label>Port</label><input name="port" type="number" min="1" max="65535" value="27017"><label>Max players</label><input name="maxPlayers" type="number" min="1" max="64" value="8"><label>Description</label><textarea name="description" maxlength="256" rows="4"></textarea><label><input style="width:auto" type="checkbox" name="passworded"> Passworded</label><button type="submit">Create Server + Download Kit</button></form></div></body></html>`);
});

app.post('/host', async (req, res, next) => {
  try {
    if (!ALLOW_PUBLIC_SUBMISSIONS) return res.status(403).send('Public server submissions are disabled.');
    const payload = formToServerPayload(req.body || {}, { verified: AUTO_VERIFY_PUBLIC_SUBMISSIONS, hidden: false });
    const { server, token } = makeServerAndToken(payload);
    const kitUrl = `/api/server-kit.zip?token=${encodeURIComponent(token)}`;
    res.type('html').send(`<!doctype html><html><head><title>Server Created</title><style>body{font-family:system-ui;background:#0d0f16;color:#fff;max-width:840px;margin:40px auto;padding:0 20px}a{color:#8ab4ff}.card{background:#171b27;border:1px solid #2a3144;border-radius:16px;padding:22px;margin:18px 0}pre{background:#0b0d13;border-radius:10px;padding:12px;display:block;overflow:auto}</style></head><body><h1>Server created</h1><div class="card"><p><strong>${escapeHtml(server.name)}</strong> is ready.</p><p>Download this kit and keep the link/token private:</p><p><a href="${escapeHtml(kitUrl)}">Download Swifly Server Kit</a></p><p>Server ID:</p><pre>${escapeHtml(server.id)}</pre><p>Public API list:</p><pre>${escapeHtml(baseUrl(req))}/api/servers</pre><p>The server appears only after heartbeat.ps1 starts.</p></div><p><a href="/host">Create another server</a></p></body></html>`);
  } catch (error) {
    next(error);
  }
});

app.get('/api/server-kit.zip', async (req, res, next) => {
  try {
    const token = String(req.query.token || '');
    const server = tokenToServer(token);
    if (!server) return res.status(404).json({ error: 'invalid token' });
    const zip = await makeServerKitZip(req, token, server);
    res.setHeader('content-type', 'application/zip');
    res.setHeader('content-disposition', `attachment; filename="swifly-server-${server.id}.zip"`);
    res.send(zip);
  } catch (error) {
    next(error);
  }
});

app.post('/api/heartbeat', async (req, res, next) => {
  try {
    const token = bearerToken(req);
    const serverFromToken = tokenToServer(token);
    if (!serverFromToken) return res.status(401).json({ error: 'invalid token' });

    const body = heartbeatSchema.parse(req.body || {});
    const now = Date.now();
    const server = {
      ...serverFromToken,
      ...body,
      address: body.address || clientIp(req),
      lastHeartbeatMs: now,
      lastHeartbeatAt: new Date(now).toISOString(),
    };

    activeServers.set(server.id, server);
    pruneExpired();

    res.json({ ok: true, server: publicServer(server) });
  } catch (error) {
    next(error);
  }
});

app.get('/api/servers', (_req, res) => {
  pruneExpired();
  const servers = [...activeServers.values()]
    .filter((server) => server.verified !== false && server.hidden !== true && server.address)
    .sort((a, b) => (b.players || 0) - (a.players || 0) || (b.lastHeartbeatMs || 0) - (a.lastHeartbeatMs || 0))
    .map(publicServer);
  res.json(servers);
});

app.get('/api/admin/servers', requireAdmin, (_req, res) => {
  pruneExpired();
  res.json([...activeServers.values()].map(publicServer));
});

app.delete('/api/admin/servers/:id', requireAdmin, (req, res) => {
  activeServers.delete(req.params.id);
  res.status(204).end();
});

app.use((error, _req, res, _next) => {
  if (error instanceof z.ZodError) return res.status(400).json({ error: 'validation failed', details: error.errors });
  console.error(error);
  res.status(500).json({ error: 'internal server error' });
});

app.listen(PORT, () => console.log(`Swifly no-db registry listening on ${PORT}`));
